### ISSUE TITLE
修改项目名称

### ISSUE THREAD

**Issue by peng1999** [drivelens/drivelens#12]
现暂定为
> 英文：DiskMagic
> 中文：磁盘魔术师

**Comment by t123yh** [comment]
中文名称暂定为：磁盘综合工具。

**Comment by peng1999** [comment]
但是我认为中英文名应当对应。不如先想一个中文名再取英文名。如果发布之前还没有更好的名字，就用`磁盘魔术师`好了。

**Comment by peng1999** [comment]
改名为Drivelens

**Comment by peng1999** [comment]
已修改项目名。
中文：驱动镜
英文：drivelens
